export const theme = {
    colors: {
        surface: '#fff9ec',
        surfaceDim: '#dfdacd',
        surfaceBright: '#fff9ec',
        surfaceContainerLowest: '#ffffff',
        surfaceContainerLow: '#f9f3e6',
        surfaceContainer: '#f3ede0',
        surfaceContainerHigh: '#eee8db',
        surfaceContainerHighest: '#e8e2d5',
        onSurface: '#1d1c14',
        onSurfaceVariant: '#4d4540',
        inverseSurface: '#333028',
        inverseOnSurface: '#f6f0e3',
        outline: '#7e7570',
        outlineVariant: '#d0c4be',
        primary: '#000000',
        onPrimary: '#ffffff',
        secondary: '#785915',
        onSecondary: '#ffffff',
        error: '#ba1a1a',
        onError: '#ffffff',
        background: '#fff9ec',
        onBackground: '#1d1c14',
        // Executive & Brand Accents
        obsidian: '#1C1917',
        bronzeBase: '#B8934A',
        bronzeHover: '#997328',
        bronzeBadge: '#F5EEDB',
        // Semantics
        successBase: '#059669',
        successPing: '#10B981',
        successWash: '#ECFDF5',
        dangerBase: '#DC2626',
        dangerSevere: '#E11D48',
        dangerWash: '#FEF2F2',
        warningBase: '#D97706',
        // Structural
        boneBorder: '#E5DDD0',
        boneBorderDark: '#DDD3C1',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 40,
        gutter: 24,
        margin: 40,
    },
    rounded: {
        sm: 4,
        DEFAULT: 8,
        md: 12,
        lg: 16, // rounded-2xl
        xl: 24, // rounded-3xl
        full: 9999,
    },
    typography: {
        displayXl: { fontSize: 48, fontWeight: '600', letterSpacing: -1.44 },
        headlineLg: { fontSize: 32, fontWeight: '600', letterSpacing: -0.64 },
        headlineMd: { fontSize: 22, fontWeight: '600', letterSpacing: -0.33 },
        headlineSm: { fontSize: 18, fontWeight: '600', letterSpacing: -0.18 },
        bodyLg: { fontSize: 16, fontWeight: '400', letterSpacing: -0.08 },
        bodyMd: { fontSize: 14, fontWeight: '400' },
        bodySm: { fontSize: 12, fontWeight: '400', letterSpacing: 0.12 },
        labelMd: { fontSize: 13, fontWeight: '500', letterSpacing: -0.13 },
        labelSm: { fontSize: 11, fontWeight: '500', letterSpacing: 0.22 },
        monoMetric: { fontSize: 24, fontWeight: '600', letterSpacing: -0.72 },
    }
};
